.TH "DBTree" 3 "4 Jan 2010" "Version Version2" "PHPDatabaseTree" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DBTree \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDBTree\fP ($dbc, $id, $table, $frontPtr, $backPtr)"
.br
.ti -1c
.RI "\fBsetLinks\fP ($dbc, $id, $table, $frontPtr, $backPtr)"
.br
.ti -1c
.RI "\fBgetProperty\fP ()"
.br
.ti -1c
.RI "\fBgetLinks\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file DBTree.php.
.SH "Member Function Documentation"
.PP 
.SS "\fBDBTree\fP ($ dbc, $ id, $ table, $ frontPtr, $ backPtr)"
.PP
Definition at line 20 of file DBTree.php.
.SS "getLinks ()"
.PP
Definition at line 58 of file DBTree.php.
.SS "getProperty ()"
.PP
Definition at line 54 of file DBTree.php.
.SS "setLinks ($ dbc, $ id, $ table, $ frontPtr, $ backPtr)"
.PP
Definition at line 37 of file DBTree.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for PHPDatabaseTree from the source code.
