.TH "C:/xampplite/htdocs/dbtree/mysqli_connect.php" 3 "4 Jan 2010" "Version Version2" "PHPDatabaseTree" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/xampplite/htdocs/dbtree/mysqli_connect.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$dbc\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$dbc"\fBInitial value:\fP
.PP
.nf
 @mysqli_connect (DB_HOST, DB_USER, DB_PASSWORD, DB_NAME)
       OR die ('Could not connect to MySQL: ' . mysqli_connect_error() )
.fi
.PP
Definition at line 14 of file mysqli_connect.php.
.SH "Author"
.PP 
Generated automatically by Doxygen for PHPDatabaseTree from the source code.
