.TH "PassWords" 3 "4 Jan 2010" "Version Version2" "PHPDatabaseTree" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PassWords \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBrandom_password\fP ($length)"
.br
.ti -1c
.RI "static \fBsanitize\fP ($pass)"
.br
.ti -1c
.RI "static \fBencrypt\fP ($pass)"
.br
.ti -1c
.RI "static \fBisSame\fP ($pass, $str)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file PassWords.php.
.SH "Member Function Documentation"
.PP 
.SS "static encrypt ($ pass)\fC [static]\fP"
.PP
Definition at line 25 of file PassWords.php.
.SS "static isSame ($ pass, $ str)\fC [static]\fP"
.PP
Definition at line 29 of file PassWords.php.
.SS "static random_password ($ length)\fC [static]\fP"
.PP
Definition at line 9 of file PassWords.php.
.SS "static sanitize ($ pass)\fC [static]\fP"
.PP
Definition at line 21 of file PassWords.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for PHPDatabaseTree from the source code.
