.TH "TreeList" 3 "4 Jan 2010" "Version Version2" "PHPDatabaseTree" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TreeList \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlistAll\fP ($dbTreeObj)"
.br
.ti -1c
.RI "\fBlistLinks\fP ($dbTreeLink)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file TreeList.php.
.SH "Member Function Documentation"
.PP 
.SS "listAll ($ dbTreeObj)"
.PP
Definition at line 14 of file TreeList.php.
.SS "listLinks ($ dbTreeLink)"
.PP
Definition at line 26 of file TreeList.php.

.SH "Author"
.PP 
Generated automatically by Doxygen for PHPDatabaseTree from the source code.
